name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout repo
    - uses: actions/checkout@v4

    # Cache build artifacts to speed up workflow
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # Install Rust (automatically uses stable)
    - uses: dtolnay/rust-toolchain@stable

    # Check code compiles
    - name: Cargo Check
      run: cargo check --verbose

    # Run Clippy for linting
    - name: Clippy Lints
      run: cargo clippy --all-targets --all-features -- -D warnings

    # Check formatting (will fail if not formatted)
    - name: Format Check
      run: cargo fmt --all -- --check

    # Build project
    - name: Build
      run: cargo build --verbose

    # Run tests on single thread
    - name: Run Tests (Single Thread)
      run: cargo test --verbose -- --test-threads=1
